/*
 * This source file was generated by the Gradle 'init' task
 */
package org.valor6800.formatter

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

class FormatterPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("org.valor6800.formatter")

        // Verify the result
        assertNotNull(project.tasks.findByName("format"))
        assertNotNull(project.tasks.findByName("lint"))
    }
}
