/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.11/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    `maven-publish`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    id("com.gradle.plugin-publish") version "1.3.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test framework
            useKotlinTest("2.0.20")
        }

        // Create a new test suite
        val functionalTest by registering(JvmTestSuite::class) {
            // Use Kotlin Test framework
            useKotlinTest("2.0.20")

            dependencies {
                // functionalTest test suite depends on the production code in tests
                implementation(project())
            }

            targets {
                all {
                    // This test suite should run after the built-in test suite has run its tests
                    testTask.configure { shouldRunAfter(test) } 
                }
            }
        }
    }
}

//gradlePlugin {
//    // Define the plugin
//    val formatter by plugins.creating {
//        id = "org.frc.wpiformat.formatter"
//        implementationClass = "org.frc.wpiformat.formatter.FormatterPlugin"
//    }
//}

gradlePlugin.testSourceSets.add(sourceSets["functionalTest"])

tasks.named<Task>("check") {
    // Include functionalTest as part of the check lifecycle
    dependsOn(testing.suites.named("functionalTest"))
}

group = "org.valor6800.formatter"
version = "1.0"

gradlePlugin {
    website = "https://github.com/ishan-karmakar/wpiformat-plugin"
    vcsUrl = "https://github.com/ishan-karmakar/wpiformat-plugin"
    plugins {
        create("formatterPlugin") {
            id = "org.valor6800.formatter"
            displayName = "Plugin for formatting (mainly) FRC repositories with wpiformat"
            description = "This plugin provides the format and lint tasks that run wpiformat under the hood"
            tags = listOf("formatter")
            implementationClass = "org.valor6800.formatter.FormatterPlugin"
        }
    }
}
